name: Type Check
on:
  workflow_call:

jobs:
  type-check:
    name: Type check
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - uses: actions/checkout@v4

      - run: |
          pip install poetry
          poetry install

      - name: Run check
        run: >
          poetry run
          mypy
          hwi.py
          hwilib/_base58.py
          hwilib/_bech32.py
          hwilib/_cli.py
          hwilib/commands.py
          hwilib/common.py
          hwilib/descriptor.py
          hwilib/devices/bitbox02.py
          hwilib/devices/coldcard.py
          hwilib/devices/digitalbitbox.py
          hwilib/devices/jade.py
          hwilib/devices/__init__.py
          hwilib/devices/keepkey.py
          hwilib/devices/ledger.py
          hwilib/devices/trezor.py
          hwilib/errors.py
          hwilib/_script.py
          hwilib/_serialize.py
          hwilib/tx.py
          hwilib/hwwclient.py
          hwilib/__init__.py
          hwilib/key.py
          hwilib/udevinstaller.py
